### ISSUE TITLE
Policy Priority Inference: A Computational Method for the Analysis of Sustainable Development

### ISSUE THREAD

**Issue by BethWoodTuring** [alan-turing-institute/podcast#45]
Omar Guerrero - aiming to publish 18 May 2020

**Comment by edwardchalstrey1** [comment]
Similar to #22

**Comment by edwardchalstrey1** [comment]
Paper - https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3604041

**Comment by edwardchalstrey1** [comment]
Other links:

https://www.turing.ac.uk/research/impact-stories/supercharging-sustainable-development

https://www.technologyreview.com/2020/05/29/1002404/united-nations-computer-agents-simulation-boost-global-sustainable-development-goals/?_cldee=amR1bmdhdGVAdHVyaW5nLmFjLnVr&recipientid=contact-17a13f9018f7e811a96e00224801377b-cef1a8d1445b431bb62c1a23f139cae6&esid=7856b79a-7ca6-ea11-a812-000d3a7f195f

**Comment by edwardchalstrey1** [comment]
http://oguerr.com/ppi/
