### ISSUE TITLE
The Disinformation Chain

### ISSUE THREAD

**Issue by edwardchalstrey1** [alan-turing-institute/podcast#63]
[Claudia Flores-Saviaga](http://saviaga.com/) reached out to me on Twitter and would like to talk about her research - she is a PhD student and Facebook research fellow

Work is about the negative effect of social media disinformation on democracy and covid etc

**Comment by AALLDDAA** [comment]
Excellent. Lets get her on.
________________________________

**Comment by edwardchalstrey1** [comment]
Slides from her talk on the topic: https://drive.google.com/file/d/1RYNrI-nsO1HnvMlrqh_bJy1QsSw4H2XO/view
